/*
 * PlayMenuBuild.java
 *
 * Created on October 18, 2012, 11:59 AM
 */

package thelastpromise;

import javax.swing.JOptionPane;

/**
 *
 * @author  100032528
 */
public class PlayMenuBuild extends javax.swing.JFrame {

    public boolean warning = true;
    /** Creates new form PlayMenuBuild */
    public PlayMenuBuild() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jCheckBox1 = new javax.swing.JCheckBox();

        jButton3.setText("Tutorial");
        jButton3.setName("new"); // NOI18N

        jToggleButton1.setText("New User");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("New Game");
        jButton1.setName("new"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Load Game");
        jButton2.setName("new"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Main Menu");
        jButton4.setName("new"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Enter a Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Enter a Password");

        jScrollPane1.setViewportView(jTextPane1);

        jCheckBox1.setText("Create New User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jCheckBox1)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 char[] password = jPasswordField1.getPassword();
 String user = jTextPane1.getText();
 if((password.length > 0 && user.length() > 0) || (warning == false &&
         password.length == 0 && user.length() == 0))
 {
    String pass = "";
    for(int i = 0; i < password.length; i++)
    {
        pass+=password[i];
    }
    if(jCheckBox1.isSelected())
    {
        SaveLoad.newLogin(pass,user);
    }
    if(password.length == 0 || SaveLoad.login(pass, user)) 
    {
        boolean start = false;
        LogHandling.logMessage("Hi "+user);
        StartGame a = new StartGame();
        //ask about number of players
        String[] playerOptions = {"Story Mode","Bot battle","1 Player battle","2 Players battle"};
        int n = JOptionPane.showOptionDialog(null,
        "Please select the game mode the you want to play.",
        "Players",JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,null, playerOptions,playerOptions[2]);
        if(n==0)
        { a.storyGame(1); start = true; }
        else if(n==1)
        {a.randomGame(100); start=true;}
        else if(n==2)
        {
            //ask who you want to play as
            String[] playAs = {"Story Mode","Azdens","The Society of Souls"};
            int p = JOptionPane.showOptionDialog(null,
            "Who do you want to play as in this game?",
            "Players",JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,null, playAs,playAs[1]);
            if(p==0)
            {a.storyGame(1); start = true;}
            if(p==1)
            {a.randomGame(101); start = true;}
            else if(p==2)
            {a.randomGame(102); start = true;}
        }
        else if(n==3)
        { a.randomGame(103); start = true; }
        if(start==true){MainMenu.close(); Sound.stopSound();}
    }
 }
 else if(password.length == 0 && user.length() == 0)
 {
     LogHandling.logError("   Warning! Your game data will not be secure if you" +
             " don't enter a username and a password!!!!!\nEnter them or push "
             + "play again to play without them.");
     warning = false;
 }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 char[] password = jPasswordField1.getPassword();
 String user = jTextPane1.getText();
 if((password.length > 0 && user.length() > 0) || (warning == false &&
         password.length == 0 && user.length() == 0))
 {
    String pass = "";
    for(int i = 0; i < password.length; i++)
    {
        pass+=password[i];
    }
    if(jCheckBox1.isSelected())
    {
        SaveLoad.newLogin(pass,user);
    }
    if(password.length == 0 || SaveLoad.login(pass, user)) 
    {
        LogHandling.logMessage("Hi "+user);
        StartGame b = new StartGame();
        b.startFromFile("Test");
        MainMenu.close();
    }
 }
 else if(password.length == 0 && user.length() == 0)
 {
     LogHandling.logError("   Warning! Your game data will not be secure if you" +
             " don't enter a username and a password!!!!!\nEnter them or push "
             + "play again to play without them.");
     warning = false;
 }

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 MainMenu a = new MainMenu();
 a.run();
}//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayMenuBuild().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
